-- CreateEnum
CREATE TYPE "ProjectRole" AS ENUM ('PROJECT_MANAGER', 'FRONTEND_DEVELOPER', 'BACKEND_DEVELOPER', 'DEVELOPER', 'UI_UX_DESIGNER', 'QA_ENGINEER', 'PRODUCT_MANAGER');

-- AlterTable
ALTER TABLE "project_members" ADD COLUMN     "role" "ProjectRole" NOT NULL DEFAULT 'DEVELOPER';
